import { getTour } from '../supabase/tour.js';
import { trackPageView } from '../supabase/supabaseFunctions.js';

trackPageView('Chabad');

const markers = [
    


    { person: 'Baal Shem Tov', birth: 1698, passing: 1760, expertise: 'Chassidus', background: 'Chassidic', name: 'Yisrael', picture: 'none', latitude: 48.84487, longitude: 25.72586, aka: 'Besht', major_works: '0', number: '1', difficulty: '1.0', city: 'Tovste', country: 'Ukraine', biography: 'The Baal Shem Tov, also known as the Besht, was a revolutionary figure in Jewish mysticism and founder of Hasidic Judaism. His teachings emphasized the importance of joyful prayer, simplicity, and direct connection with God for all Jews. The Besht\'s legacy continues to inspire millions, fostering spiritual renewal and devotion in Jewish communities worldwide.', birthday: '18 Elul', yahrtzeit: '6 Sivan', abbreviation: 'BST', from: 1698, to: 1717, city_of_passing: 'Medzhybizh', country_of_passing: 'Ukraine', person_hebrew: 'בעל שם טוב', name_hebrew: 'ישראל', wikipedia_link: 'https://en.wikipedia.org/wiki/Baal_Shem_Tov', latitude_of_passing: 49.43672, longitude_of_passing: 27.4041},
    { person: 'Mezritcher Maggid', birth: 1704, passing: 1772, expertise: 'Chassidus', background: 'Chassidic', name: 'Dovber', picture: 'none', latitude: 50.73895, longitude: 24.64829, aka: 'Maggid of Mezritch, R Dovber of Mezritch', major_works: 'Maggid Devorov Leyaakov, Ohr Torah', number: '1', difficulty: '2.0', city: 'Lokachi', country: 'Ukraine', biography: 'The Mezritcher Maggid, R Dovber of Mezritch, was a prominent Hasidic leader and spiritual successor to the Baal Shem Tov, the founder of Hasidism. R Dovber served as the primary transmitter of the Baal Shem Tov\'s teachings, spreading the teachings of Hasidism throughout Eastern Europe. His disciples included many future leaders of the Hasidic movement.', birthday: '0', yahrtzeit: '19 Kislev', abbreviation: 'DM', from: 1704, to: 1716, city_of_passing: 'Mezhirichi', country_of_passing: 'Ukraine', person_hebrew: 'מזריטשער מגיד', name_hebrew: 'דובער', wikipedia_link: 'https://en.wikipedia.org/wiki/Dov_Ber_of_Mezeritch', latitude_of_passing: 50.6598, longitude_of_passing: 26.86311},
    { person: 'Mezritcher Maggid', birth: 1704, passing: 1772, expertise: 'Chassidus', background: 'Chassidic', name: 'Dovber', picture: 'none', latitude: 49.84495, longitude: 24.02859, aka: 'Maggid of Mezritch, R Dovber of Mezritch', major_works: 'Maggid Devorov Leyaakov, Ohr Torah', number: '2', difficulty: '2.0', city: 'Lviv', country: 'Ukraine', biography: 'The Mezritcher Maggid, R Dovber of Mezritch, was a prominent Hasidic leader and spiritual successor to the Baal Shem Tov, the founder of Hasidism. R Dovber served as the primary transmitter of the Baal Shem Tov\'s teachings, spreading the teachings of Hasidism throughout Eastern Europe. His disciples included many future leaders of the Hasidic movement.', birthday: '0', yahrtzeit: '19 Kislev', abbreviation: 'DM', from: 1717, to: 1719, city_of_passing: 'Mezhirichi', country_of_passing: 'Ukraine', person_hebrew: 'מזריטשער מגיד', name_hebrew: 'דובער', wikipedia_link: 'https://en.wikipedia.org/wiki/Dov_Ber_of_Mezeritch', latitude_of_passing: 50.6598, longitude_of_passing: 26.86311},
    { person: 'Baal Shem Tov', birth: 1698, passing: 1760, expertise: 'Chassidus', background: 'Chassidic', name: 'Yisrael', picture: 'none', latitude: 50.0833, longitude: 25.14379, aka: 'Besht', major_works: '0', number: '2', difficulty: '1.0', city: 'Brody', country: 'Ukraine', biography: 'The Baal Shem Tov, also known as the Besht, was a revolutionary figure in Jewish mysticism and founder of Hasidic Judaism. His teachings emphasized the importance of joyful prayer, simplicity, and direct connection with God for all Jews. The Besht\'s legacy continues to inspire millions, fostering spiritual renewal and devotion in Jewish communities worldwide.', birthday: '18 Elul', yahrtzeit: '6 Sivan', abbreviation: 'BST', from: 1718, to: 1718, city_of_passing: 'Medzhybizh', country_of_passing: 'Ukraine', person_hebrew: 'בעל שם טוב', name_hebrew: 'ישראל', wikipedia_link: 'https://en.wikipedia.org/wiki/Baal_Shem_Tov', latitude_of_passing: 49.43672, longitude_of_passing: 27.4041},
    { person: 'Baal Shem Tov', birth: 1698, passing: 1760, expertise: 'Chassidus', background: 'Chassidic', name: 'Yisrael', picture: 'none', latitude: 48.3158, longitude: 25.09834, aka: 'Besht', major_works: '0', number: '3', difficulty: '1.0', city: 'Kosiv', country: 'Ukraine', biography: 'The Baal Shem Tov, also known as the Besht, was a revolutionary figure in Jewish mysticism and founder of Hasidic Judaism. His teachings emphasized the importance of joyful prayer, simplicity, and direct connection with God for all Jews. The Besht\'s legacy continues to inspire millions, fostering spiritual renewal and devotion in Jewish communities worldwide.', birthday: '18 Elul', yahrtzeit: '6 Sivan', abbreviation: 'BST', from: 1719, to: 1729, city_of_passing: 'Medzhybizh', country_of_passing: 'Ukraine', person_hebrew: 'בעל שם טוב', name_hebrew: 'ישראל', wikipedia_link: 'https://en.wikipedia.org/wiki/Baal_Shem_Tov', latitude_of_passing: 49.43672, longitude_of_passing: 27.4041},
    { person: 'Mezritcher Maggid', birth: 1704, passing: 1772, expertise: 'Chassidus', background: 'Chassidic', name: 'Dovber', picture: 'none', latitude: 48.67305, longitude: 28.85695, aka: 'Maggid of Mezritch, R Dovber of Mezritch', major_works: 'Maggid Devorov Leyaakov, Ohr Torah', number: '3', difficulty: '2.0', city: 'Tulchyn', country: 'Ukraine', biography: 'The Mezritcher Maggid, R Dovber of Mezritch, was a prominent Hasidic leader and spiritual successor to the Baal Shem Tov, the founder of Hasidism. R Dovber served as the primary transmitter of the Baal Shem Tov\'s teachings, spreading the teachings of Hasidism throughout Eastern Europe. His disciples included many future leaders of the Hasidic movement.', birthday: '0', yahrtzeit: '19 Kislev', abbreviation: 'DM', from: 1720, to: 1759, city_of_passing: 'Mezhirichi', country_of_passing: 'Ukraine', person_hebrew: 'מזריטשער מגיד', name_hebrew: 'דובער', wikipedia_link: 'https://en.wikipedia.org/wiki/Dov_Ber_of_Mezeritch', latitude_of_passing: 50.6598, longitude_of_passing: 26.86311},
    { person: 'Baal Shem Tov', birth: 1698, passing: 1760, expertise: 'Chassidus', background: 'Chassidic', name: 'Yisrael', picture: 'none', latitude: 48.96297, longitude: 25.44358, aka: 'Besht', major_works: '0', number: '4', difficulty: '1.0', city: 'Yazlovets', country: 'Ukraine', biography: 'The Baal Shem Tov, also known as the Besht, was a revolutionary figure in Jewish mysticism and founder of Hasidic Judaism. His teachings emphasized the importance of joyful prayer, simplicity, and direct connection with God for all Jews. The Besht\'s legacy continues to inspire millions, fostering spiritual renewal and devotion in Jewish communities worldwide.', birthday: '18 Elul', yahrtzeit: '6 Sivan', abbreviation: 'BST', from: 1730, to: 1730, city_of_passing: 'Medzhybizh', country_of_passing: 'Ukraine', person_hebrew: 'בעל שם טוב', name_hebrew: 'ישראל', wikipedia_link: 'https://en.wikipedia.org/wiki/Baal_Shem_Tov', latitude_of_passing: 49.43672, longitude_of_passing: 27.4041},
    { person: 'Baal Shem Tov', birth: 1698, passing: 1760, expertise: 'Chassidus', background: 'Chassidic', name: 'Yisrael', picture: 'none', latitude: 48.84487, longitude: 25.72886, aka: 'Besht', major_works: '0', number: '5', difficulty: '1.0', city: 'Tovste', country: 'Ukraine', biography: 'The Baal Shem Tov, also known as the Besht, was a revolutionary figure in Jewish mysticism and founder of Hasidic Judaism. His teachings emphasized the importance of joyful prayer, simplicity, and direct connection with God for all Jews. The Besht\'s legacy continues to inspire millions, fostering spiritual renewal and devotion in Jewish communities worldwide.', birthday: '18 Elul', yahrtzeit: '6 Sivan', abbreviation: 'BST', from: 1731, to: 1739, city_of_passing: 'Medzhybizh', country_of_passing: 'Ukraine', person_hebrew: 'בעל שם טוב', name_hebrew: 'ישראל', wikipedia_link: 'https://en.wikipedia.org/wiki/Baal_Shem_Tov', latitude_of_passing: 49.43672, longitude_of_passing: 27.4041},
    { person: 'Baal Shem Tov', birth: 1698, passing: 1760, expertise: 'Chassidus', background: 'Chassidic', name: 'Yisrael', picture: 'none', latitude: 49.43672, longitude: 27.4071, aka: 'Besht', major_works: '0', number: '6', difficulty: '1.0', city: 'Medzhybizh', country: 'Ukraine', biography: 'The Baal Shem Tov, also known as the Besht, was a revolutionary figure in Jewish mysticism and founder of Hasidic Judaism. His teachings emphasized the importance of joyful prayer, simplicity, and direct connection with God for all Jews. The Besht\'s legacy continues to inspire millions, fostering spiritual renewal and devotion in Jewish communities worldwide.', birthday: '18 Elul', yahrtzeit: '6 Sivan', abbreviation: 'BST', from: 1740, to: 1760, city_of_passing: 'Medzhybizh', country_of_passing: 'Ukraine', person_hebrew: 'בעל שם טוב', name_hebrew: 'ישראל', wikipedia_link: 'https://en.wikipedia.org/wiki/Baal_Shem_Tov', latitude_of_passing: 49.43672, longitude_of_passing: 27.4041},
    { person: 'Alter Rebbe', birth: 1745, passing: 1812, expertise: 'Halacha, Responsa, Chassidus', background: 'Chassidic', name: 'Shneur Zalman Borukhovich', picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Schneur_Zalman_of_Liadi.jpg/800px-Schneur_Zalman_of_Liadi.jpg', latitude: 55.02321, longitude: 30.79567, aka: 'Baal Hatanya, R Shneur Zalman of Liady', major_works: 'Shulchan Aruch Harav, Tanya, Torah Ohr, Sefer Hama\'amarim', number: '1', difficulty: '1.0', city: 'Liozna', country: 'Belarus', biography: 'The Alter Rebbe, R Schneur Zalman of Liadi, was the founder of Chabad Chassidism and a prominent figure in Jewish mysticism. His seminal work, the Tanya, delves into the depths of Jewish spirituality, guiding seekers towards a deeper understanding of Godliness and personal growth.', birthday: '18 Elul', yahrtzeit: '24 Teves', abbreviation: 'BT', from: 1745, to: 1800, city_of_passing: 'Liady', country_of_passing: 'Belarus', person_hebrew: 'אלטער רבי', name_hebrew: 'שניאור זלמן בורוכוביץ', wikipedia_link: 'https://en.wikipedia.org/wiki/Shneur_Zalman_of_Liadi', latitude_of_passing: 53.61362, longitude_of_passing: 28.69972},
    { person: 'Mezritcher Maggid', birth: 1704, passing: 1772, expertise: 'Chassidus', background: 'Chassidic', name: 'Dovber', picture: 'none', latitude: 50.6598, longitude: 26.86611, aka: 'Maggid of Mezritch, R Dovber of Mezritch', major_works: 'Maggid Devorov Leyaakov, Ohr Torah', number: '4', difficulty: '2.0', city: 'Mezhirichi', country: 'Ukraine', biography: 'The Mezritcher Maggid, R Dovber of Mezritch, was a prominent Hasidic leader and spiritual successor to the Baal Shem Tov, the founder of Hasidism. R Dovber served as the primary transmitter of the Baal Shem Tov\'s teachings, spreading the teachings of Hasidism throughout Eastern Europe. His disciples included many future leaders of the Hasidic movement.', birthday: '0', yahrtzeit: '19 Kislev', abbreviation: 'DM', from: 1760, to: 1772, city_of_passing: 'Mezhirichi', country_of_passing: 'Ukraine', person_hebrew: 'מזריטשער מגיד', name_hebrew: 'דובער', wikipedia_link: 'https://en.wikipedia.org/wiki/Dov_Ber_of_Mezeritch', latitude_of_passing: 50.6598, longitude_of_passing: 26.86311},
    { person: 'Mitteler Rebbe', birth: 1773, passing: 1827, expertise: 'Kabbalah, Chassidus, Mussar', background: 'Chassidic', name: 'Dovber Schneuri', picture: 'none', latitude: 55.02321, longitude: 30.79867, aka: '0', major_works: 'Biurei Hazohar, Shaarei Teshuva, Kuntres Hahispaalus, Mamorei Admor Ha\'emtzo\'i', number: '1', difficulty: '2.0', city: 'Liozna', country: 'Belarus', biography: 'R Dovber Schneuri, known as the Mitteler Rebbe, was the second Rebbe of the Chabad-Lubavitch Hasidic dynasty. He was the son and successor of R Schneur Zalman of Liadi, the founder of Chabad Hasidism. R Dovber was revered for his scholarship, piety, and leadership.', birthday: '9 Kislev', yahrtzeit: '9 Kislev', abbreviation: 'DS', from: 1773, to: 1800, city_of_passing: 'Lyubavichi', country_of_passing: 'Russia', person_hebrew: 'מיטעלער רבי', name_hebrew: 'דובער שניאורי', wikipedia_link: 'https://en.wikipedia.org/wiki/Dovber_Schneuri', latitude_of_passing: 54.83339, longitude_of_passing: 30.95641},
    { person: 'Rebbe Tzemach Tzedek', birth: 1789, passing: 1866, expertise: 'Talmud, Responsa, Chassidus', background: 'Chassidic', name: 'Menachem Mendel Schneersohn', picture: 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Tzemachtzedek2.jpg', latitude: 55.02321, longitude: 30.79267, aka: 'Tzemach Tzedek', major_works: 'Tzemach Tzedek, Derech Mitzvosecha, Ohr Hatorah, Chidushim Al Hashas', number: '1', difficulty: '3.0', city: 'Liozna', country: 'Belarus', biography: 'R Menachem Mendel Schneersohn, known as the Tzemach Tzedek, was the third Rebbe of the Chabad-Lubavitch Hasidic dynasty. He was revered for his profound Torah scholarship, leadership, and devotion to his followers. His teachings encompassed a wide range of subjects, including Hasidic philosophy, Jewish law, and mysticism.', birthday: '29 Elul', yahrtzeit: '13 Nissan', abbreviation: 'MMS', from: 1789, to: 1800, city_of_passing: 'Lyubavichi', country_of_passing: 'Russia', person_hebrew: 'רבי צמח צדק', name_hebrew: 'מנחם מענדל שניאורסון', wikipedia_link: 'https://en.wikipedia.org/wiki/Menachem_Mendel_Schneersohn', latitude_of_passing: 54.83339, longitude_of_passing: 30.95641},
    { person: 'Alter Rebbe', birth: 1745, passing: 1812, expertise: 'Halacha, Responsa, Chassidus', background: 'Chassidic', name: 'Shneur Zalman Borukhovich', picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Schneur_Zalman_of_Liadi.jpg/800px-Schneur_Zalman_of_Liadi.jpg', latitude: 53.61362, longitude: 28.69972, aka: 'Baal Hatanya, R Shneur Zalman of Liady', major_works: 'Shulchan Aruch Harav, Tanya, Torah Ohr, Sefer Hama\'amarim', number: '2', difficulty: '1.0', city: 'Liady', country: 'Belarus', biography: 'The Alter Rebbe, R Schneur Zalman of Liadi, was the founder of Chabad Chassidism and a prominent figure in Jewish mysticism. His seminal work, the Tanya, delves into the depths of Jewish spirituality, guiding seekers towards a deeper understanding of Godliness and personal growth.', birthday: '18 Elul', yahrtzeit: '24 Teves', abbreviation: 'BT', from: 1801, to: 1812, city_of_passing: 'Liady', country_of_passing: 'Belarus', person_hebrew: 'אלטער רבי', name_hebrew: 'שניאור זלמן בורוכוביץ', wikipedia_link: 'https://en.wikipedia.org/wiki/Shneur_Zalman_of_Liadi', latitude_of_passing: 53.61362, longitude_of_passing: 28.69972},
    { person: 'Mitteler Rebbe', birth: 1773, passing: 1827, expertise: 'Kabbalah, Chassidus, Mussar', background: 'Chassidic', name: 'Dovber Schneuri', picture: 'none', latitude: 53.61362, longitude: 28.70272, aka: '0', major_works: 'Biurei Hazohar, Shaarei Teshuva, Kuntres Hahispaalus, Mamorei Admor Ha\'emtzo\'i', number: '2', difficulty: '2.0', city: 'Liady', country: 'Belarus', biography: 'R Dovber Schneuri, known as the Mitteler Rebbe, was the second Rebbe of the Chabad-Lubavitch Hasidic dynasty. He was the son and successor of R Schneur Zalman of Liadi, the founder of Chabad Hasidism. R Dovber was revered for his scholarship, piety, and leadership.', birthday: '9 Kislev', yahrtzeit: '9 Kislev', abbreviation: 'DS', from: 1801, to: 1812, city_of_passing: 'Lyubavichi', country_of_passing: 'Russia', person_hebrew: 'מיטעלער רבי', name_hebrew: 'דובער שניאורי', wikipedia_link: 'https://en.wikipedia.org/wiki/Dovber_Schneuri', latitude_of_passing: 54.83339, longitude_of_passing: 30.95641},
    { person: 'Rebbe Tzemach Tzedek', birth: 1789, passing: 1866, expertise: 'Talmud, Responsa, Chassidus', background: 'Chassidic', name: 'Menachem Mendel Schneersohn', picture: 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Tzemachtzedek2.jpg', latitude: 53.61362, longitude: 28.69672, aka: 'Tzemach Tzedek', major_works: 'Tzemach Tzedek, Derech Mitzvosecha, Ohr Hatorah, Chidushim Al Hashas', number: '2', difficulty: '3.0', city: 'Liady', country: 'Belarus', biography: 'R Menachem Mendel Schneersohn, known as the Tzemach Tzedek, was the third Rebbe of the Chabad-Lubavitch Hasidic dynasty. He was revered for his profound Torah scholarship, leadership, and devotion to his followers. His teachings encompassed a wide range of subjects, including Hasidic philosophy, Jewish law, and mysticism.', birthday: '29 Elul', yahrtzeit: '13 Nissan', abbreviation: 'MMS', from: 1801, to: 1812, city_of_passing: 'Lyubavichi', country_of_passing: 'Russia', person_hebrew: 'רבי צמח צדק', name_hebrew: 'מנחם מענדל שניאורסון', wikipedia_link: 'https://en.wikipedia.org/wiki/Menachem_Mendel_Schneersohn', latitude_of_passing: 54.83339, longitude_of_passing: 30.95641},
    { person: 'Mitteler Rebbe', birth: 1773, passing: 1827, expertise: 'Kabbalah, Chassidus, Mussar', background: 'Chassidic', name: 'Dovber Schneuri', picture: 'none', latitude: 54.83339, longitude: 30.95641, aka: '0', major_works: 'Biurei Hazohar, Shaarei Teshuva, Kuntres Hahispaalus, Mamorei Admor Ha\'emtzo\'i', number: '3', difficulty: '2.0', city: 'Lyubavichi', country: 'Russia', biography: 'R Dovber Schneuri, known as the Mitteler Rebbe, was the second Rebbe of the Chabad-Lubavitch Hasidic dynasty. He was the son and successor of R Schneur Zalman of Liadi, the founder of Chabad Hasidism. R Dovber was revered for his scholarship, piety, and leadership.', birthday: '9 Kislev', yahrtzeit: '9 Kislev', abbreviation: 'DS', from: 1813, to: 1827, city_of_passing: 'Lyubavichi', country_of_passing: 'Russia', person_hebrew: 'מיטעלער רבי', name_hebrew: 'דובער שניאורי', wikipedia_link: 'https://en.wikipedia.org/wiki/Dovber_Schneuri', latitude_of_passing: 54.83339, longitude_of_passing: 30.95641},
    { person: 'Rebbe Tzemach Tzedek', birth: 1789, passing: 1866, expertise: 'Talmud, Responsa, Chassidus', background: 'Chassidic', name: 'Menachem Mendel Schneersohn', picture: 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Tzemachtzedek2.jpg', latitude: 54.83339, longitude: 30.959410000000002, aka: 'Tzemach Tzedek', major_works: 'Tzemach Tzedek, Derech Mitzvosecha, Ohr Hatorah, Chidushim Al Hashas', number: '3', difficulty: '3.0', city: 'Lyubavichi', country: 'Russia', biography: 'R Menachem Mendel Schneersohn, known as the Tzemach Tzedek, was the third Rebbe of the Chabad-Lubavitch Hasidic dynasty. He was revered for his profound Torah scholarship, leadership, and devotion to his followers. His teachings encompassed a wide range of subjects, including Hasidic philosophy, Jewish law, and mysticism.', birthday: '29 Elul', yahrtzeit: '13 Nissan', abbreviation: 'MMS', from: 1813, to: 1866, city_of_passing: 'Lyubavichi', country_of_passing: 'Russia', person_hebrew: 'רבי צמח צדק', name_hebrew: 'מנחם מענדל שניאורסון', wikipedia_link: 'https://en.wikipedia.org/wiki/Menachem_Mendel_Schneersohn', latitude_of_passing: 54.83339, longitude_of_passing: 30.95641},
    { person: 'Rebbe Maharash', birth: 1834, passing: 1882, expertise: 'Chassidus', background: 'Chassidic', name: 'Shmuel Schneersohn', picture: 'none', latitude: 54.83339, longitude: 30.95341, aka: 'Maharash', major_works: 'Likutei Torah Toras Shmuel, Sefer Hasichos Toras Shmuel', number: '1', difficulty: '5.0', city: 'Lyubavichi', country: 'Russia', biography: 'R Shmuel Schneersohn, known as the Rebbe Maharash, was the fourth Rebbe of Chabad-Lubavitch. The Rebbe Maharash is famous for his maamorim and letters as well as his inspirational leadership during Anti-Semitic persecution in Russia.', birthday: '2 Iyar', yahrtzeit: '13 Tishrei', abbreviation: 'SS', from: 1834, to: 1882, city_of_passing: 'Lyubavichi', country_of_passing: 'Russia', person_hebrew: 'רבי מהר"ש', name_hebrew: 'שמואל שניאורסון', wikipedia_link: 'https://en.wikipedia.org/wiki/Shmuel_Schneersohn', latitude_of_passing: 54.83339, longitude_of_passing: 30.95641},
    { person: 'Rebbe Rashab', birth: 1860, passing: 1920, expertise: 'Chassidus', background: 'Chassidic', name: 'Sholom Dovber Schneersohn', picture: 'https://upload.wikimedia.org/wikipedia/commons/0/06/Image-RebbeRashab.jpg', latitude: 54.83639, longitude: 30.95641, aka: 'Rashab', major_works: 'Sefer Hama\'amorim, Toras Sholom, Kuntres Ho\'avoda', number: '1', difficulty: '4.0', city: 'Lyubavichi', country: 'Russia', biography: 'R Sholom Dovber Schneersohn, also known as the Rebbe Rashab, was the fifth Rebbe of the Chabad-Lubavitch Hasidic dynasty. In addition to authoring many scholarly treatises on chassidus, he established the renowned Lubavitch yeshiva Tomchei Temimim, which integrates Chassidic study with traditional rabbinic scholarship.', birthday: '20 Cheshvan', yahrtzeit: '2 Nissan', abbreviation: 'SDS', from: 1860, to: 1914, city_of_passing: 'Rostov', country_of_passing: 'Russia', person_hebrew: 'רבי רש"ב', name_hebrew: 'שלום דובער שניאורסון', wikipedia_link: 'https://en.wikipedia.org/wiki/Sholom_Dovber_Schneersohn', latitude_of_passing: 47.22165, longitude_of_passing: 39.70961},
    { person: 'Frierdiker Rebbe', birth: 1880, passing: 1950, expertise: 'Chassidus, Philosophy, History', background: 'Chassidic', name: 'Yosef Yitzchak Schneersohn', picture: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/FrierdigerRebbePassportPic.jpg', latitude: 54.83039, longitude: 30.95641, aka: 'Rebbe Rayatz, Previous Rebbe, Rayatz', major_works: 'Likutei Diburim, Sefer Hamamorim, Sefer Hazichronos', number: '1', difficulty: '2.0', city: 'Lyubavichi', country: 'Russia', biography: 'The Frierdiker Rebbe, R Yosef Yitzchak Schneersohn, was the sixth Rebbe of the Chabad-Lubavitch Hasidic dynasty. Guiding Soviet Jewry through the terrors of the Soviet regime, he continued to inspire with unwavering faith and resilience, emphasized the importance of Torah study, Jewish outreach, and steadfast commitment to Jewish observance.', birthday: '12 Tammuz', yahrtzeit: '10 Shevat', abbreviation: 'RR', from: 1880, to: 1914, city_of_passing: 'Brooklyn', country_of_passing: 'USA', person_hebrew: 'פריערדיקער רבי', name_hebrew: 'יוסף יצחק שניאורסון', wikipedia_link: 'https://en.wikipedia.org/wiki/Yosef_Yitzchak_Schneersohn', latitude_of_passing: 40.6526, longitude_of_passing: -73.94972},
    { person: 'Lubavitcher Rebbe', birth: 1902, passing: 1994, expertise: 'Tanach, Talmud, Halacha, Responsa, Chassidus', background: 'Chassidic', name: 'Menachem Mendel Schneersohn', picture: 'https://upload.wikimedia.org/wikipedia/commons/6/68/Rabbi_Menachem_Mendel_Schneerson2.jpg', latitude: 46.97586, longitude: 31.99697, aka: 'The Rebbe', major_works: 'Likutei Sichos, Sefer Hamamorim, Biurim Lepirush Rashi, Igros Kodesh', number: '1', difficulty: '1.0', city: 'Mykolaiv', country: 'Ukraine', biography: 'R Menachem Mendel Schneersohn, the 7th rebbe of the Chabad-Lubavitch Hasidic dynasty, illuminated the 20th century with his outstanding scholarship and leadership. Beginning in his lifetime, his students and emissaries continue to spread his message throughout the world, forming the largest Jewish outreach movement in the world.', birthday: '11 Nissan', yahrtzeit: '3 Tammuz', abbreviation: 'LR', from: 1902, to: 1906, city_of_passing: 'Brooklyn', country_of_passing: 'USA', person_hebrew: 'ליובאוויטשער רבי', name_hebrew: 'מנחם מענדל שניאורסון', wikipedia_link: 'https://en.wikipedia.org/wiki/Menachem_Mendel_Schneerson', latitude_of_passing: 40.6526, longitude_of_passing: -73.94972},
    { person: 'Lubavitcher Rebbe', birth: 1902, passing: 1994, expertise: 'Tanach, Talmud, Halacha, Responsa, Chassidus', background: 'Chassidic', name: 'Menachem Mendel Schneersohn', picture: 'https://upload.wikimedia.org/wikipedia/commons/6/68/Rabbi_Menachem_Mendel_Schneerson2.jpg', latitude: 48.46802, longitude: 35.04177, aka: 'The Rebbe', major_works: 'Likutei Sichos, Sefer Hamamorim, Biurim Lepirush Rashi, Igros Kodesh', number: '2', difficulty: '1.0', city: 'Dnipro', country: 'Ukraine', biography: 'R Menachem Mendel Schneersohn, the 7th rebbe of the Chabad-Lubavitch Hasidic dynasty, illuminated the 20th century with his outstanding scholarship and leadership. Beginning in his lifetime, his students and emissaries continue to spread his message throughout the world, forming the largest Jewish outreach movement in the world.', birthday: '11 Nissan', yahrtzeit: '3 Tammuz', abbreviation: 'LR', from: 1907, to: 1927, city_of_passing: 'Brooklyn', country_of_passing: 'USA', person_hebrew: 'ליובאוויטשער רבי', name_hebrew: 'מנחם מענדל שניאורסון', wikipedia_link: 'https://en.wikipedia.org/wiki/Menachem_Mendel_Schneerson', latitude_of_passing: 40.6526, longitude_of_passing: -73.94972},
    { person: 'Frierdiker Rebbe', birth: 1880, passing: 1950, expertise: 'Chassidus, Philosophy, History', background: 'Chassidic', name: 'Yosef Yitzchak Schneersohn', picture: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/FrierdigerRebbePassportPic.jpg', latitude: 47.22165, longitude: 39.70961, aka: 'Rebbe Rayatz, Previous Rebbe, Rayatz', major_works: 'Likutei Diburim, Sefer Hamamorim, Sefer Hazichronos', number: '2', difficulty: '2.0', city: 'Rostov', country: 'Russia', biography: 'The Frierdiker Rebbe, R Yosef Yitzchak Schneersohn, was the sixth Rebbe of the Chabad-Lubavitch Hasidic dynasty. Guiding Soviet Jewry through the terrors of the Soviet regime, he continued to inspire with unwavering faith and resilience, emphasized the importance of Torah study, Jewish outreach, and steadfast commitment to Jewish observance.', birthday: '12 Tammuz', yahrtzeit: '10 Shevat', abbreviation: 'RR', from: 1915, to: 1923, city_of_passing: 'Brooklyn', country_of_passing: 'USA', person_hebrew: 'פריערדיקער רבי', name_hebrew: 'יוסף יצחק שניאורסון', wikipedia_link: 'https://en.wikipedia.org/wiki/Yosef_Yitzchak_Schneersohn', latitude_of_passing: 40.6526, longitude_of_passing: -73.94972},
    { person: 'Rebbe Rashab', birth: 1860, passing: 1920, expertise: 'Chassidus', background: 'Chassidic', name: 'Sholom Dovber Schneersohn', picture: 'https://upload.wikimedia.org/wikipedia/commons/0/06/Image-RebbeRashab.jpg', latitude: 47.22165, longitude: 39.71261, aka: 'Rashab', major_works: 'Sefer Hama\'amorim, Toras Sholom, Kuntres Ho\'avoda', number: '2', difficulty: '4.0', city: 'Rostov', country: 'Russia', biography: 'R Sholom Dovber Schneersohn, also known as the Rebbe Rashab, was the fifth Rebbe of the Chabad-Lubavitch Hasidic dynasty. In addition to authoring many scholarly treatises on chassidus, he established the renowned Lubavitch yeshiva Tomchei Temimim, which integrates Chassidic study with traditional rabbinic scholarship.', birthday: '20 Cheshvan', yahrtzeit: '2 Nissan', abbreviation: 'SDS', from: 1915, to: 1920, city_of_passing: 'Rostov', country_of_passing: 'Russia', person_hebrew: 'רבי רש"ב', name_hebrew: 'שלום דובער שניאורסון', wikipedia_link: 'https://en.wikipedia.org/wiki/Sholom_Dovber_Schneersohn', latitude_of_passing: 47.22165, longitude_of_passing: 39.70961},
    { person: 'Frierdiker Rebbe', birth: 1880, passing: 1950, expertise: 'Chassidus, Philosophy, History', background: 'Chassidic', name: 'Yosef Yitzchak Schneersohn', picture: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/FrierdigerRebbePassportPic.jpg', latitude: 59.94068, longitude: 30.2965, aka: 'Rebbe Rayatz, Previous Rebbe, Rayatz', major_works: 'Likutei Diburim, Sefer Hamamorim, Sefer Hazichronos', number: '3', difficulty: '2.0', city: 'St Petersburg', country: 'Russia', biography: 'The Frierdiker Rebbe, R Yosef Yitzchak Schneersohn, was the sixth Rebbe of the Chabad-Lubavitch Hasidic dynasty. Guiding Soviet Jewry through the terrors of the Soviet regime, he continued to inspire with unwavering faith and resilience, emphasized the importance of Torah study, Jewish outreach, and steadfast commitment to Jewish observance.', birthday: '12 Tammuz', yahrtzeit: '10 Shevat', abbreviation: 'RR', from: 1924, to: 1929, city_of_passing: 'Brooklyn', country_of_passing: 'USA', person_hebrew: 'פריערדיקער רבי', name_hebrew: 'יוסף יצחק שניאורסון', wikipedia_link: 'https://en.wikipedia.org/wiki/Yosef_Yitzchak_Schneersohn', latitude_of_passing: 40.6526, longitude_of_passing: -73.94972},
    { person: 'Lubavitcher Rebbe', birth: 1902, passing: 1994, expertise: 'Tanach, Talmud, Halacha, Responsa, Chassidus', background: 'Chassidic', name: 'Menachem Mendel Schneersohn', picture: 'https://upload.wikimedia.org/wikipedia/commons/6/68/Rabbi_Menachem_Mendel_Schneerson2.jpg', latitude: 52.51704, longitude: 13.39486, aka: 'The Rebbe', major_works: 'Likutei Sichos, Sefer Hamamorim, Biurim Lepirush Rashi, Igros Kodesh', number: '3', difficulty: '1.0', city: 'Berlin', country: 'Germany', biography: 'R Menachem Mendel Schneersohn, the 7th rebbe of the Chabad-Lubavitch Hasidic dynasty, illuminated the 20th century with his outstanding scholarship and leadership. Beginning in his lifetime, his students and emissaries continue to spread his message throughout the world, forming the largest Jewish outreach movement in the world.', birthday: '11 Nissan', yahrtzeit: '3 Tammuz', abbreviation: 'LR', from: 1928, to: 1932, city_of_passing: 'Brooklyn', country_of_passing: 'USA', person_hebrew: 'ליובאוויטשער רבי', name_hebrew: 'מנחם מענדל שניאורסון', wikipedia_link: 'https://en.wikipedia.org/wiki/Menachem_Mendel_Schneerson', latitude_of_passing: 40.6526, longitude_of_passing: -73.94972},
    { person: 'Frierdiker Rebbe', birth: 1880, passing: 1950, expertise: 'Chassidus, Philosophy, History', background: 'Chassidic', name: 'Yosef Yitzchak Schneersohn', picture: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/FrierdigerRebbePassportPic.jpg', latitude: 56.9494, longitude: 24.10818, aka: 'Rebbe Rayatz, Previous Rebbe, Rayatz', major_works: 'Likutei Diburim, Sefer Hamamorim, Sefer Hazichronos', number: '4', difficulty: '2.0', city: 'Riga', country: 'Latvia', biography: 'The Frierdiker Rebbe, R Yosef Yitzchak Schneersohn, was the sixth Rebbe of the Chabad-Lubavitch Hasidic dynasty. Guiding Soviet Jewry through the terrors of the Soviet regime, he continued to inspire with unwavering faith and resilience, emphasized the importance of Torah study, Jewish outreach, and steadfast commitment to Jewish observance.', birthday: '12 Tammuz', yahrtzeit: '10 Shevat', abbreviation: 'RR', from: 1930, to: 1933, city_of_passing: 'Brooklyn', country_of_passing: 'USA', person_hebrew: 'פריערדיקער רבי', name_hebrew: 'יוסף יצחק שניאורסון', wikipedia_link: 'https://en.wikipedia.org/wiki/Yosef_Yitzchak_Schneersohn', latitude_of_passing: 40.6526, longitude_of_passing: -73.94972},
    { person: 'Lubavitcher Rebbe', birth: 1902, passing: 1994, expertise: 'Tanach, Talmud, Halacha, Responsa, Chassidus', background: 'Chassidic', name: 'Menachem Mendel Schneersohn', picture: 'https://upload.wikimedia.org/wikipedia/commons/6/68/Rabbi_Menachem_Mendel_Schneerson2.jpg', latitude: 48.85589, longitude: 2.32004, aka: 'The Rebbe', major_works: 'Likutei Sichos, Sefer Hamamorim, Biurim Lepirush Rashi, Igros Kodesh', number: '4', difficulty: '1.0', city: 'Paris', country: 'France', biography: 'R Menachem Mendel Schneersohn, the 7th rebbe of the Chabad-Lubavitch Hasidic dynasty, illuminated the 20th century with his outstanding scholarship and leadership. Beginning in his lifetime, his students and emissaries continue to spread his message throughout the world, forming the largest Jewish outreach movement in the world.', birthday: '11 Nissan', yahrtzeit: '3 Tammuz', abbreviation: 'LR', from: 1933, to: 1940, city_of_passing: 'Brooklyn', country_of_passing: 'USA', person_hebrew: 'ליובאוויטשער רבי', name_hebrew: 'מנחם מענדל שניאורסון', wikipedia_link: 'https://en.wikipedia.org/wiki/Menachem_Mendel_Schneerson', latitude_of_passing: 40.6526, longitude_of_passing: -73.94972},
    { person: 'Frierdiker Rebbe', birth: 1880, passing: 1950, expertise: 'Chassidus, Philosophy, History', background: 'Chassidic', name: 'Yosef Yitzchak Schneersohn', picture: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/FrierdigerRebbePassportPic.jpg', latitude: 52.23672, longitude: 21.06843, aka: 'Rebbe Rayatz, Previous Rebbe, Rayatz', major_works: 'Likutei Diburim, Sefer Hamamorim, Sefer Hazichronos', number: '5', difficulty: '2.0', city: 'Warsaw', country: 'Poland', biography: 'The Frierdiker Rebbe, R Yosef Yitzchak Schneersohn, was the sixth Rebbe of the Chabad-Lubavitch Hasidic dynasty. Guiding Soviet Jewry through the terrors of the Soviet regime, he continued to inspire with unwavering faith and resilience, emphasized the importance of Torah study, Jewish outreach, and steadfast commitment to Jewish observance.', birthday: '12 Tammuz', yahrtzeit: '10 Shevat', abbreviation: 'RR', from: 1934, to: 1939, city_of_passing: 'Brooklyn', country_of_passing: 'USA', person_hebrew: 'פריערדיקער רבי', name_hebrew: 'יוסף יצחק שניאורסון', wikipedia_link: 'https://en.wikipedia.org/wiki/Yosef_Yitzchak_Schneersohn', latitude_of_passing: 40.6526, longitude_of_passing: -73.94972},
    { person: 'Frierdiker Rebbe', birth: 1880, passing: 1950, expertise: 'Chassidus, Philosophy, History', background: 'Chassidic', name: 'Yosef Yitzchak Schneersohn', picture: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/FrierdigerRebbePassportPic.jpg', latitude: 40.6526, longitude: -73.95272, aka: 'Rebbe Rayatz, Previous Rebbe, Rayatz', major_works: 'Likutei Diburim, Sefer Hamamorim, Sefer Hazichronos', number: '6', difficulty: '2.0', city: 'Brooklyn', country: 'USA', biography: 'The Frierdiker Rebbe, R Yosef Yitzchak Schneersohn, was the sixth Rebbe of the Chabad-Lubavitch Hasidic dynasty. Guiding Soviet Jewry through the terrors of the Soviet regime, he continued to inspire with unwavering faith and resilience, emphasized the importance of Torah study, Jewish outreach, and steadfast commitment to Jewish observance.', birthday: '12 Tammuz', yahrtzeit: '10 Shevat', abbreviation: 'RR', from: 1940, to: 1950, city_of_passing: 'Brooklyn', country_of_passing: 'USA', person_hebrew: 'פריערדיקער רבי', name_hebrew: 'יוסף יצחק שניאורסון', wikipedia_link: 'https://en.wikipedia.org/wiki/Yosef_Yitzchak_Schneersohn', latitude_of_passing: 40.6526, longitude_of_passing: -73.94972},
    { person: 'Lubavitcher Rebbe', birth: 1902, passing: 1994, expertise: 'Tanach, Talmud, Halacha, Responsa, Chassidus', background: 'Chassidic', name: 'Menachem Mendel Schneersohn', picture: 'https://upload.wikimedia.org/wikipedia/commons/6/68/Rabbi_Menachem_Mendel_Schneerson2.jpg', latitude: 40.6556, longitude: -73.94972, aka: 'The Rebbe', major_works: 'Likutei Sichos, Sefer Hamamorim, Biurim Lepirush Rashi, Igros Kodesh', number: '5', difficulty: '1.0', city: 'Brooklyn', country: 'USA', biography: 'R Menachem Mendel Schneersohn, the 7th rebbe of the Chabad-Lubavitch Hasidic dynasty, illuminated the 20th century with his outstanding scholarship and leadership. Beginning in his lifetime, his students and emissaries continue to spread his message throughout the world, forming the largest Jewish outreach movement in the world.', birthday: '11 Nissan', yahrtzeit: '3 Tammuz', abbreviation: 'LR', from: 1941, to: 1994, city_of_passing: 'Brooklyn', country_of_passing: 'USA', person_hebrew: 'ליובאוויטשער רבי', name_hebrew: 'מנחם מענדל שניאורסון', wikipedia_link: 'https://en.wikipedia.org/wiki/Menachem_Mendel_Schneerson', latitude_of_passing: 40.6526, longitude_of_passing: -73.94972},




]


// Track if we're currently in a pause
let isPaused = false;
let playInterval = 1;
let videoSpeed = 1;
let frameSpeed = 200;
let visibleMarkers = [];
let visibleMarkersPeople = [];
let pauses = []; // will be filled from API

// Fetch pauses from your backend API


async function fetchPauses() {
  try {
    // instead of fetch() from Flask, we now call your Supabase function
    const result = await getTour({ tour: "Chabad" });

    // result.data already contains only Chabad rows
    pauses = result.data || [];

    console.log("Pauses loaded:", pauses);

  } catch (err) {
    console.error("Failed to fetch pauses:", err);
  }
}


// Call fetch once DOM is loaded
document.addEventListener("DOMContentLoaded", fetchPauses);

// Function to display markers filtered by year during animation
function displayMarkersByTimeAnimate(markersData, visibleMarkers, visibleMarkersPeople) {
    const timeValue = document.getElementById('year-slider').noUiSlider.get();
    const currentMarkersData = markersData.filter(marker => marker.from <= timeValue && marker.to >= timeValue);

    currentMarkersData.forEach(marker => {
        marker.fromYear = marker.from == timeValue;
        marker.toYear = marker.to == timeValue;
        marker.birthYear = marker.birth == timeValue;
        marker.passYear = marker.passing == timeValue;
    });

    displayMarkers(currentMarkersData, visibleMarkers);
}

// Function to start playing the timeline
function startPlaying(videoSpeed, pauses) {
    clearInterval(playInterval);
    frameSpeed = 200 / videoSpeed;

    playInterval = setInterval(() => {
        if (isPaused) return;

        const slider = document.getElementById('year-slider');
        const currentValue = parseInt(slider.noUiSlider.get());
        const newValue = currentValue + 1;

        // Check if the new value is in our pause years
        const pauseInfo = pauses.find(pause => pause.year === newValue);

        if (pauseInfo) {
            slider.noUiSlider.set(newValue);
            displayMarkersByTimeAnimate(markers, visibleMarkers, visibleMarkersPeople);

            // Display information about this pause point
            displayPauseInfo(pauseInfo);

            isPaused = true;

            setTimeout(() => {
                isPaused = false;
            }, pauseInfo.duration + 500);
        } else {
            // Normal progression
            document.getElementById('icon-space').innerHTML = '';
            document.getElementById('name-content').innerHTML = '';
            slider.noUiSlider.set(newValue);
            displayMarkersByTimeAnimate(markers, visibleMarkers, visibleMarkersPeople);
        }
    }, frameSpeed);
}

// Function to stop playing
function stopPlaying() {
    clearInterval(playInterval);
}

// Initialize the year slider
var yearSlider = document.getElementById('year-slider');

noUiSlider.create(yearSlider, {
    start: 1744,
    connect: [true, false],
    range: {
        'min': 1744,
        'max': 2000
    },
    step: 1,
    tooltips: true,
    format: {
        to: function (value) { return Math.round(value); },
        from: function (value) { return Number(value); }
    },
    pips: {
        mode: 'values',
        values: [1800, 1900],
        density: 10,
        format: {
            to: function (value) { return value.toString(); }
        }
    }
});

// Popup hover setup
window.popup = document.getElementById('popup');
window.popupMessage = document.querySelector('.popup-message');

document.addEventListener('mouseover', handleHoverPopup);

document.addEventListener('mousemove', event => {
    popup.style.left = event.pageX + 10 + "px";
    popup.style.top = event.pageY - 28 + "px";
});

document.addEventListener('mouseout', event => {
    if (event.target.classList.contains('popup-button')) {
        popup.classList.remove('visible');
    }
});

// Play button event
window.playButton = document.getElementById('play-button');
playButton.addEventListener('click', () => {
    if (!playButton.checked) {
        if (pauses.length === 0) {
            console.warn("No pauses loaded yet! Please wait for data.");
            return;
        }
        playButton.checked = true;
        playButton.classList.add('paused');
        startPlaying(videoSpeed, pauses);
    } else {
        playButton.checked = false;
        playButton.classList.remove('paused');
        stopPlaying();
    }
});
